version: '3.8'

services:

  frontend:
    build: ./services/frontend
    ports:
      - "8050:8050"
    container_name: dash_frontend

    environment:
      - BASE_URL=http://backend:8000
    networks:
      - app-network


networks:
  app-network: